export const ADD_ALERT_ITEM = 'ADD_ALERT_ITEM';
export const ADD_ALERT_ITEM_ARRAY = 'ADD_ALERT_ITEM_ARRAY';
export const REMOVE_ALERT_ITEM = 'REMOVE_ALERT_ITEM';
export const REMOVE_ALERT_ITEM_ARRAY = 'REMOVE_ALERT_ITEM_ARRAY';
export const CLEAR_ALERTS = 'CLEAR_ALERTS';