export const ALERT_ACTION = {
    ADD_ALERT_ITEM: 'ADD_ALERT_ITEM',
    ADD_ALERT_ITEM_ARRAY: 'ADD_ALERT_ITEM_ARRAY',
    REMOVE_ALERT_ITEM: 'REMOVE_ALERT_ITEM',
    REMOVE_ALERT_ITEM_ARRAY: 'REMOVE_ALERT_ITEM_ARRAY',
    CLEAR_ALERTS: 'CLEAR_ALERTS'
};

export const DEMO_ACTIONS = {
    DEMO_LOADER: 'DEMO_LOADER',
    DEMO_ALERTS: 'DEMO_ALERTS'
};

export const LOADER_ACTION = {
    ADD_LOADER_ITEM: 'ADD_LOADER_ITEM',
    REMOVE_LOADER_ITEM: 'REMOVE_LOADER_ITEM',
    CLEAR_LOADER: 'CLEAR_LOADER'
};